import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as vscode from "vscode";

const t = vscode.l10n.t;
const MARKER = "local-merge-request";
const CLI_PATH_KEY = "lreview.cliWrapper";
const SKILL_NAME = "local-merge-request";
const isWindows = process.platform === "win32";

async function exists(p: string): Promise<boolean> {
  try {
    await fs.lstat(p);
    return true;
  } catch {
    return false;
  }
}

function wrapperScript(cli: string): string {
  const exec = process.execPath;
  if (isWindows) {
    return [
      "@echo off",
      `rem ${MARKER}`,
      "where node >nul 2>nul",
      `if %errorlevel%==0 ( node "${cli}" %* ) else ( set ELECTRON_RUN_AS_NODE=1& "${exec}" "${cli}" %* )`,
      "",
    ].join("\r\n");
  }
  const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  return [
    "#!/bin/sh",
    `# ${MARKER}: generated by the Local Merge Request VS Code extension`,
    `CLI=${q(cli)}`,
    'if command -v node >/dev/null 2>&1; then exec node "$CLI" "$@"; fi',
    `ELECTRON_RUN_AS_NODE=1 exec ${q(exec)} "$CLI" "$@"`,
    "",
  ].join("\n");
}

/** Copies the bundled CLI to a location that survives extension updates. */
async function stageCli(context: vscode.ExtensionContext): Promise<string> {
  const dir = context.globalStorageUri.fsPath;
  await fs.mkdir(dir, { recursive: true });
  const target = path.join(dir, "cli.js");
  await fs.copyFile(path.join(context.extensionPath, "dist", "cli.js"), target);
  return target;
}

async function writeWrapper(file: string, cli: string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.rm(file, { force: true });
  await fs.writeFile(file, wrapperScript(cli), { mode: 0o755 });
}

export async function installCli(context: vscode.ExtensionContext): Promise<void> {
  const defaultDir = path.join(os.homedir(), ".local", "bin");
  const choice = await vscode.window.showQuickPick(
    [
      { label: defaultDir, description: t("recommended"), dir: defaultDir as string | undefined },
      { label: t("Choose a folder…"), dir: undefined },
    ],
    { placeHolder: t("Where should the lreview command be installed?") },
  );
  if (!choice) return;
  let dir = choice.dir;
  if (!dir) {
    const picked = await vscode.window.showOpenDialog({ canSelectFiles: false, canSelectFolders: true, openLabel: t("Install here") });
    if (!picked?.[0]) return;
    dir = picked[0].fsPath;
  }
  const file = path.join(dir, isWindows ? "lreview.cmd" : "lreview");
  if (await exists(file)) {
    const content = await fs.readFile(file, "utf8").catch(() => "");
    const stat = await fs.lstat(file);
    if (stat.isSymbolicLink() || !content.includes(MARKER)) {
      const replace = t("Replace");
      const ok = await vscode.window.showWarningMessage(t("{0} already exists and was not created by this extension. Replace it?", file), { modal: true }, replace);
      if (ok !== replace) return;
    }
  }
  await writeWrapper(file, await stageCli(context));
  await context.globalState.update(CLI_PATH_KEY, file);
  const onPath = (process.env.PATH ?? "").split(path.delimiter).some((p) => path.resolve(p) === path.resolve(dir!));
  const message = onPath
    ? t("lreview installed in {0}.", file)
    : t("lreview installed in {0}. This folder is not on your PATH: add it to use lreview from a terminal.", file);
  void vscode.window.showInformationMessage(message);
}

/** Keeps an installed CLI in sync with the running extension version and VS Code binary. */
export async function refreshInstalledCli(context: vscode.ExtensionContext): Promise<void> {
  const file = context.globalState.get<string>(CLI_PATH_KEY);
  if (!file) return;
  try {
    const content = await fs.readFile(file, "utf8");
    if (!content.includes(MARKER)) return;
    const cli = await stageCli(context);
    const expected = wrapperScript(cli);
    if (content !== expected) await writeWrapper(file, cli);
  } catch {
    // Removed by the user: nothing to refresh.
  }
}

export async function installSkill(context: vscode.ExtensionContext): Promise<void> {
  const dir = path.join(os.homedir(), ".claude", "skills", SKILL_NAME);
  const target = path.join(dir, "SKILL.md");
  const source = await fs.readFile(path.join(context.extensionPath, "skill", "SKILL.md"), "utf8");
  if (await exists(dir)) {
    if ((await fs.lstat(dir)).isSymbolicLink()) {
      void vscode.window.showInformationMessage(t("{0} is a symbolic link (development install): left unchanged.", dir));
      return;
    }
    const current = await fs.readFile(target, "utf8").catch(() => null);
    if (current === source) {
      void vscode.window.showInformationMessage(t("The Claude Code skill is already up to date in {0}.", dir));
      return;
    }
    if (current !== null) {
      const replace = t("Replace");
      const ok = await vscode.window.showWarningMessage(t("{0} already exists. Replace it with the bundled version?", target), { modal: true }, replace);
      if (ok !== replace) return;
    }
  }
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(target, source);
  void vscode.window.showInformationMessage(
    t("Claude Code skill installed in {0}. Ask Claude to \"process the review\" in a repository with open threads.", dir),
  );
}
